# ---------- BUILD STAGE ----------
FROM node:24-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npx nest build


# ---------- RUNTIME STAGE ----------
FROM node:24-alpine

WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist

ARG EXPOSE_PORT=3000
EXPOSE ${EXPOSE_PORT}

CMD ["node", "dist/main.js"]
